apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zeg40uiv5-nodejs 
  janus-idp.io/tekton: zeg40uiv5-nodejs
  backstage.io/kubernetes-id: zeg40uiv5-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zeg40uiv5-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml