apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zeg40uiv5-nodejs-gitops
  description: This is GitOps manifest for zeg40uiv5-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=zeg40uiv5-nodejs
    backstage.io/kubernetes-id: zeg40uiv5-nodejs 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: zeg40uiv5-nodejs-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:zeg40uiv5-nodejs
